return {
	-- Parser generator to boost highlighting
	"nvim-treesitter/nvim-treesitter",
	event = "VeryLazy",
	cmd = { "TSUpdate", "TSInstall", "TSLog", "TSUninstall" },
	build = ":TSUpdate",

	opts = {
		-- Install parsers synchronously (only applied to `ensure_installed`)
		sync_install = false,
		-- Automatically install missing parsers when entering buffer
		auto_install = true,
		indent = { enable = true },
		highlight = { enable = true },
		folds = { enable = true },
		-- A list of parser names, or "all"
		ensure_installed = {
			"bash",
			"c,",
			"c_sharp",
			"csv",
			"diff",
			"dockerfile",
			"html",
			"hyprlang",
			"java",
			"javadoc",
			"javascript",
			"json",
			"ledger",
			"lua",
			"make",
			"markdown",
			"markdown_inline",
			"nginx",
			"properties",
			"python",
			"regex",
			"sql",
			"ssh_config",
			"toml",
			"typescript",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
			"zsh",
		},
	},
}
